### ISSUE TITLE
Error received when attempting to edit the calendar.

### ISSUE THREAD

**Issue by Charles082986** [vigoren/foundryvtt-simple-calendar#121]
All of my attempts to edit the calendar (either by importing from about-time or making simple changes using the Simple Calendar interface) result in an error:

When attempting to import from about-time:
```
Uncaught (in promise) Error: You may not assign the value of a world-level Setting before the Game is ready.
    at ClientSettings.set (foundry.js:1202)
    at Function.SaveYearConfiguration (index.js:1)
    at Function.importAboutTime (index.js:1)
    at N.overwriteConfirmationYes (index.js:1)
    at Dialog.submit (foundry.js:20351)
    at Dialog._onClickButton (foundry.js:20314)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
set @ foundry.js:1202
SaveYearConfiguration @ index.js:1
importAboutTime @ index.js:1
overwriteConfirmationYes @ index.js:1
submit @ foundry.js:20351
_onClickButton @ foundry.js:20314
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
async function (async)
overwriteConfirmationYes @ index.js:1
submit @ foundry.js:20351
_onClickButton @ foundry.js:20314
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

When attempting to make simple changes using the interface:
```
Simple Calendar  | Error "You may not assign the value of a world-level Setting before the Game is ready."
Error: You may not assign the value of a world-level Setting before the Game is ready.
    at ClientSettings.set (http://192.168.1.102:23401/scripts/foundry.js:1202:34)
    at Function.SaveGeneralSettings (http://192.168.1.102:23401/modules/foundryvtt-simple-calendar/index.js:1:7144)
    at N.saveClick (http://192.168.1.102:23401/modules/foundryvtt-simple-calendar/index.js:1:88022)
    at HTMLButtonElement.dispatch (http://192.168.1.102:23401/scripts/jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (http://192.168.1.102:23401/scripts/jquery.min.js:2:41048)
error @ index.js:1
saveClick @ index.js:1
async function (async)
saveClick @ index.js:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Foundry Version 0.8.6
Simple Calendar 1.2.67

**Comment by Charles082986** [comment]
This was a fresh install using the most recent version as of about 20 minutes ago.

**Comment by Charles082986** [comment]
This appears to have resolved itself after a server restart.
