### ISSUE TITLE
[BUG] Incompatibility with v10

### ISSUE THREAD

**Issue by marcstraube** [vigoren/foundryvtt-simple-calendar#381]
Hi,
I'm testing my needed modules to update to v10 and I get the following error when I load a world into a world, where the only active module is Simple Calendar:

```
foundry.js:747 Error: Error thrown in hooked function '' for hook 'init'. Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (commons.js:4082:15)
    at SchemaField.validate (commons.js:3809:37)
    at Setting.validate (commons.js:5462:35)
    at new DataModel (commons.js:5239:26)
    at new Document (commons.js:5778:3)
    at new BaseSetting (commons.js:9789:3)
    at new ClientDocumentMixin (foundry.js:12941:5)
    at new Setting (foundry.js:21171:1)
    at ClientSettings.get (foundry.js:2773:21)
    at $.LoadYearData (index.js:1:123955)
onError @ foundry.js:747
#call @ foundry.js:728
callAll @ foundry.js:681
initialize @ foundry.js:7712
window.addEventListener.once @ foundry.js:78838
```

**Foundry Information**
 - Foundry Version: 10.286
 - Game System: DnD5e
 - Simple Calendar Version: 1.3.75

**Comment by marcstraube** [comment]
Hmmm... I just saw that the current version is 2.19. Strange that the module did not update.
I'm closing this issue! Sorry for the bother!
