### ISSUE TITLE
BUG: Saving calendar configuration in v10 doesn't work

### ISSUE THREAD

**Issue by magroader** [vigoren/foundryvtt-simple-calendar#389]
I am setting up a new calendar. I tried to make some changes and click Save Configuration, but unfortunately it did not work. It also spouted this error, which may or may not be related:

```
Error "Setting Model Validation Errors
[Setting.value]: may not be undefined"
Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (https://my.foundry.url/scripts/commons.js:4090:15)
    at SchemaField.validate (https://my.foundry.url/scripts/commons.js:3817:37)
    at Setting.validate (https://my.foundry.url/scripts/commons.js:5470:35)
    at new DataModel (https://my.foundry.url/scripts/commons.js:5247:26)
    at new Document (https://my.foundry.url/scripts/commons.js:5786:3)
    at new BaseSetting (https://my.foundry.url/scripts/commons.js:9807:3)
    at new ClientDocumentMixin (https://my.foundry.url/scripts/foundry.js:12996:5)
    at new Setting (https://my.foundry.url/scripts/foundry.js:21232:1)
    at ClientSettings.get (https://my.foundry.url/scripts/foundry.js:2774:21)
    at $.LoadGeneralSettings (https://my.foundry.url/modules/foundryvtt-simple-calendar/index.js:1:123882)
    at $.SaveGeneralSettings (https://my.foundry.url/modules/foundryvtt-simple-calendar/index.js:1:125046)
    at z.saveClick (https://my.foundry.url/modules/foundryvtt-simple-calendar/index.js:1:117916)
    at HTMLButtonElement.dispatch (https://my.foundry.url/scripts/jquery.min.js:2:43064)
    at y.handle (https://my.foundry.url/scripts/jquery.min.js:2:41048)
error @ index.js:1
saveClick @ index.js:1
await in saveClick (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

I noticed a similar settings error happened when I entered my world with SimpleCalendar enabled.

**Comment by vigoren** [comment]
Are you on version 10 of foundry?
Which version of simple calendar are you running?

If you are on foundry version 10 then I don't think you are on the latest version of simple calendar.

The version should be 2.1.27

If you are on 1.3.75 you will have to uninstall and reinstall the module. Uninstalling a module doesn't delete any data so it's safe to do that.

**Comment by magroader** [comment]
Wow, yeah, I was on an old version. I wonder how that happened!

Why does it not update via the standard update button and require an uninstall/reinstall? Do other modules have similar issues?

Regardless, thanks! Also it looks cool!

**Comment by vigoren** [comment]
There was a bug in version 1.3.75's manifest that resulted in having to do a uninstall reinstall action.

Other modules should be ok.
