### ISSUE TITLE
[BUG] Can't Save custom configuration

### ISSUE THREAD

**Issue by Nyhles** [vigoren/foundryvtt-simple-calendar#463]
**Describe the bug**
When configuring a custom calendar on a new world without other modules activated, the saves are discarded. The error message displayed in the console is written down below.

**To Reproduce**
1. Open Simple Calendar
2. Configure some changes
3. Click save button
4. See error in console

**Expected behavior**
Saving the configuration.

**Screenshots**

**Foundry Information**
 - Foundry Version: Version 10 - Build 291
 - Game System: Call of Cthulhu 7th Edition (Unofficial) (V.0.9.2) / The Dark Eye (5th Edition) (V.4.2.11)
 - Simple Calendar Version: 1.3.75
 - Simple Calendar Configuration: standard

**Browser (please complete the following information):**
 - Browser Firefox, Chrome

**Additional context**
Error text from Console:
Simple Calendar  | Error "Setting Model Validation Errors
[Setting.value]: may not be undefined"
Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (http://localhost:30000/scripts/commons.js:4098:15)
    at SchemaField.validate (http://localhost:30000/scripts/commons.js:3824:37)
    at Setting.validate (http://localhost:30000/scripts/commons.js:5492:35)
    at new DataModel (http://localhost:30000/scripts/commons.js:5269:26)
    at new Document (http://localhost:30000/scripts/commons.js:5811:3)
    at new BaseSetting (http://localhost:30000/scripts/commons.js:9832:3)
    at new ClientDocumentMixin (http://localhost:30000/scripts/foundry.js:13053:5)
    at new Setting (http://localhost:30000/scripts/foundry.js:21323:1)
    at ClientSettings.get (http://localhost:30000/scripts/foundry.js:2815:21)
    at Function.LoadGeneralSettings (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:123882)

**Comment by Nyhles** [comment]
Sorry, somehow my module couldn't update beyond that version. I reinstalled it and with the current version everything works as expected.
