### ISSUE TITLE
[BUG] Warhammer Calendar is not working

### ISSUE THREAD

**Issue by geoidesic** [vigoren/foundryvtt-simple-calendar#483]
**Describe the bug**
Trying to use this with Warhammer Fantasy Role Play system. The Warhammer  Imperial calendar is one of the configurations that can be loaded. Once loaded, the correct months etc. show in the config, however, in the calendar itself it shows the Gregorian values.

There is also a console error:

```
foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'init'
#call @ foundry.js:727
callAll @ foundry.js:681
initialize @ foundry.js:7810
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:79693
foundry.js:747 Error: Error thrown in hooked function '' for hook 'init'. Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 2 packages: foundryvtt-simple-calendar, lib-wrapper]
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Setting.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseSetting (commons.js:9832:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Setting (foundry.js:21323:1)
    at ClientSettings.get (foundry.js:2815:21)
    at $.LoadYearData (index.js:1:123955)
    at J.settingUpdate (index.js:1:179498)
    at J.LoadCalendars (index.js:1:174181)
    at ee.init (index.js:1:184198)
    at Object.fn (index.js:1:206850)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7810:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
 ```
![Screenshot 2023-03-29 at 11 53 49](https://user-images.githubusercontent.com/4637995/228512032-56104ccd-9007-436d-81ed-c03b9b4b3396.png)

**To Reproduce**
1. Install the Warhammer Fantasy system
2. Install Simple Calendar
3. Apply the predefined Warhammer Imperial calendar 
4. Click Apply
5. Click Save Configuration (this causes a console error too)

```
Simple Calendar  | Error "Setting Model Validation Errors
[Setting.value]: may not be undefined"
Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (https://foundryvtt.3dmentia.com/scripts/commons.js:4098:15)
    at SchemaField.validate (https://foundryvtt.3dmentia.com/scripts/commons.js:3824:37)
    at Setting.validate (https://foundryvtt.3dmentia.com/scripts/commons.js:5492:35)
    at new DataModel (https://foundryvtt.3dmentia.com/scripts/commons.js:5269:26)
    at new Document (https://foundryvtt.3dmentia.com/scripts/commons.js:5811:3)
    at new BaseSetting (https://foundryvtt.3dmentia.com/scripts/commons.js:9832:3)
    at new ClientDocumentMixin (https://foundryvtt.3dmentia.com/scripts/foundry.js:13053:5)
    at new Setting (https://foundryvtt.3dmentia.com/scripts/foundry.js:21323:1)
    at ClientSettings.get (https://foundryvtt.3dmentia.com/scripts/foundry.js:2815:21)
    at $.LoadGeneralSettings (https://foundryvtt.3dmentia.com/modules/foundryvtt-simple-calendar/index.js:1:123882)
    at $.SaveGeneralSettings (https://foundryvtt.3dmentia.com/modules/foundryvtt-simple-calendar/index.js:1:125046)
    at z.saveClick (https://foundryvtt.3dmentia.com/modules/foundryvtt-simple-calendar/index.js:1:117916)
    at HTMLButtonElement.dispatch (https://foundryvtt.3dmentia.com/scripts/jquery.min.js:2:43064)
    at y.handle (https://foundryvtt.3dmentia.com/scripts/jquery.min.js:2:41048)
error @ index.js:1
saveClick @ index.js:1
await in saveClick (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Expected behavior**
Should work!

**Screenshots**

**Foundry Information**
 - Foundry Version: 10 build 291
 - Game System: Warhammer Fantasy Roleplay 4th Edition 6.4.0
 - Simple Calendar Version: 1.3.75
 - Simple Calendar Configuration: N/A

**Browser (please complete the following information):**
 - Browser: I tried it in all of them but lets say Brave because that's what I use in session.

**Additional context**

**Comment by geoidesic** [comment]
Uninstalled version 1.x and re-installed to get v2.x. Problem goes away.
