### ISSUE TITLE
[Bug] After importing custom calendar, Simple Calendar won't open

### ISSUE THREAD

**Issue by Rqller** [vigoren/foundryvtt-simple-calendar#502]
**Describe the bug**
I imported a custom calendar to Simple Calendars, it was made using the Donjon calendar generator: https://donjon.bin.sh/fantasy/calendar/#

After the import and saving settings, Simple Calendar closed and won't open anymore. I've tried uninstalling through Foundry VTT and uninstalling manually from %appdata% and reinstalling. 

**Foundry Information**
Version 11, build 299 - 5e version 2.2.1

Simple Calendar version 2.2.0

**Comment by vigoren** [comment]
Simple Calendar doesn't support importing from that tool. It only supports importing files that it has exported itself.

That said I tried to import a file from that tool and while it didn't work the Simple Calendar was still able to open. When you try to load the module are there any errors in the console (F12)?

**Comment by Rqller** [comment]
I get two errors:

`Simple Calendar  | Error "Cannot read properties of undefined (reading 'name')"
TypeError: Cannot read properties of undefined (reading 'name')
    at Object.MMMM (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:15618)
    at http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:16456
    at String.replace (<anonymous>)
    at K (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:16438)
    at http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:136981
    at Array.map (<anonymous>)
    at MainApp.getData (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:136887)
    at MainApp._render (http://localhost:30000/scripts/foundry.js:5770:29)
    at MainApp._render (http://localhost:30000/scripts/foundry.js:6488:17)
    at MainApp.render (http://localhost:30000/scripts/foundry.js:5727:10)
    at MainApp.render (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:137733)
    at MainApp.sceneControlButtonClick (http://localhost:30000/modules/foundryvtt-simple-calendar/index.js:1:137854)
    at SceneControls._onClickTool (http://localhost:30000/scripts/foundry.js:77079:52)
    at HTMLLIElement.dispatch (http://localhost:30000/scripts/jquery.min.js:2:43184)
    at y.handle (http://localhost:30000/scripts/jquery.min.js:2:41168)`
    
    `TypeError: An error occurred while rendering MainApp 1. Cannot read properties of undefined (reading 'getDaysForTemplate')
[Detected 1 package: foundryvtt-simple-calendar]
    at ns.daysIntoWeeks (index.js:1:206647)
    at be.Build (index.js:1:39274)
    at be.Render (index.js:1:38231)
    at Object.FullCalendar (index.js:1:181138)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:12:165)
    at Object.h [as inverse] (handlebars.min.js:27:17870)
    at Object.<anonymous> (handlebars.min.js:27:10101)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:47)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7681:10)
    at async MainApp._renderInner (foundry.js:5931:16)
    at async MainApp._renderInner (foundry.js:6499:18)
    at async MainApp._render (foundry.js:5776:19)
    at async MainApp._render (foundry.js:6488:5)`

**Comment by vigoren** [comment]
Thanks that is helpful information. You should be able to reset the calendar by opening the console (F12) and pasting this command in and hitting enter.
``` SimpleCalendar.api.configureCalendar(SimpleCalendar.api.Calendars.Gregorian);
```

That resets it to the default calendar.

**Comment by Rqller** [comment]
This worked, thank you very much! Very excited to use this in my campaign, the short bit I messed around with it, it seem really well done! :)

**Comment by vigoren** [comment]
No problem, sorry it took a while for me to get back to you.
