### ISSUE TITLE
[BUG] Recursion Error when rendering a Roll i the DSA5/TDE5 System

### ISSUE THREAD

**Issue by Lyynix** [vigoren/foundryvtt-simple-calendar#651]
**Describe the bug**
When I roll from a character sheet in the dsa5 system, an near-endless error pops up in the console. the eroor itself is caused during a "createChatMessage" Hook call, which only simple calendar and dsa5 are listening to in my world. the error disappears when deactivating simple calendar.

Note, that I have only tried this in the dsa5 system, but this might be there in other systems aswell

Ill make the error message collapsable for obvious reasons:
<details>
<summary>Full error message</summary>
foundry.js:655 Error: Error thrown in hooked function 'createChatMessage' for hook 'preCreateChatMessage'. Maximum call stack size exceeded<br>
[Detected 2 packages: foundryvtt-simple-calendar(2.4.18), system:dsa5(6.1.9)]<br>
    at Hooks.onError (foundry.js:654:24)<br>
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)<br>
    at #call (foundry.js:636:36)<br>
    at Hooks.call (foundry.js:614:38)<br>
    at #preCreateDocumentArray (foundry-esm.js:56393:46)<br>
    at async ClientDatabaseBackend._createDocuments (foundry-esm.js:56347:7)<br>
    at async ChatMessage.createDocuments (foundry-esm.js:11423:23)<br>
    at async ChatMessage.create (foundry-esm.js:11567:23)<br>
    at async DiceDSA5.renderRollCard (dsa5.js:54:8896)<br>
    at async o.basicTest (dsa5.js:57:19194)<br>
Caused by: RangeError: Maximum call stack size exceeded<br>
[Detected 2 packages: foundryvtt-simple-calendar(2.4.18), system:dsa5(6.1.9)]<br>
    at foundry-esm.js:2845:36<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:3678:37<br>
    at Array.every (<anonymous>)<br>
    at Array.equals$1 (foundry-esm.js:3672:17)<br>
    at foundry-esm.js:2850:55<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:2851:37<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:3678:37<br>
    at Array.every (<anonymous>)<br>
    at Array.equals$1 (foundry-esm.js:3672:17)<br>
    at foundry-esm.js:2850:55<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:2851:37<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:3678:37<br>
    at Array.every (<anonymous>)<br>
    at Array.equals$1 (foundry-esm.js:3672:17)<br>
    at foundry-esm.js:2850:55<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:2851:37<br>
    at Array.every (<anonymous>)<br>
    at objectsEqual (foundry-esm.js:2845:30)<br>
    at foundry-esm.js:3678:37<br>
    at Array.every (<anonymous>)<br>
    at Array.equals$1 (foundry-esm.js:3672:17)<br>
    ...
</details>

**To Reproduce**
1. Have dsa5 and simple calender installed
2. open a character sheet
3. click on any talent to roll the check
4. the check will get posted to chat, but the error is visible in the console

**Expected behavior**
well, no error would be nice

**Foundry Information**
 - Foundry Version: v12.331
 - Game System: dsa5/tde5
 - Simple Calendar Version: 2.4.18
 - Simple Calendar Configuration: aventurian calendar (TDE5 Preset)

**Browser (please complete the following information):**
 - Chrome

**Additional context**
This is an error message, however it is not noticable inside foundry. there is nothing missing in the chat message, the roll works, etc
this is mostly for informational purpose

**Comment by mhs2508** [comment]
Looks very similar to this one: https://github.com/vigoren/foundryvtt-simple-calendar/issues/582.

Same problem in my DSA5/TDE5 world.

**Comment by Akjosch** [comment]
My personal analysis of the problem (though I'm not affiliated with either the system or the module):

The "problem", if you want to call it that, is that the dsa5 system packs *a lot* of data into flags.data, including the whole `Roll` object in `flags.data.preData.roll`. Not the data of the roll as a plain old JS object, the instance of the specific class itself. And despite what the API documentation claims, ("Flag values can assume almost any data type."), those things better not be anything too complex and *certainly* shouldn't be any recursive data type, else `diffData(...)` *will* croak with the exact error message you see there. It goes like this in this case:

`flags.data.preData.roll.terms[0]._root.terms[0]._root.terms[0]._root.terms[0]._root.terms[0]._root.terms[0]._root.terms[0]._root...`

Simple Calendar isn't the cause here; using a recursive data structure inside a chat message's flag is. Simple Calendar simply triggers that problem, but *any* module which modifies a chat message's flag will do the same.

Edit: What *could* possibly help masking the issue is if Simple Calendar used `setFlag` instead of `updateSource` for settings its flag data:
https://foundryvtt.com/api/classes/client.ChatMessage.html#setFlag

**Comment by Plushtoast** [comment]
Should not happen anymore in 6.2.2 of DSA. thanks for the investigation.

**Comment by Akjosch** [comment]
That's correct - I verified it as soon as 6.2.2 was available, just to be sure.

@vigoren I suggest you close this issue, though I'd still strongly recommend using `setFlag` intead of `updateSource` if possible.
